name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Trust repository
      run: git config --global --add safe.directory /github/workspace
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Yarn install
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    - name: Write Git Hash
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: git:hash
    - name: Build React App
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: web:build
    - name: Run web test
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: web:test
    - name: Build Express.js Server
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: server:build